### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by LawnGnome** [newrelic/c-sdk#2]
While we have nothing to announce at this time, we are exploring possibilities to provide C SDK support on Windows in the medium term.

Please reach out to us if you would like to collaborate or have further questions, either here or at the [Explorers Hub](https://discuss.newrelic.com/c/build-on-new-relic/Open-Source-Agents-SDKs).

**Comment by jodeev** [comment]
Windows support is provided via OpenTelemetry! See the [OpenTelemetry CPP repository](https://github.com/open-telemetry/opentelemetry-cpp) for more information. As of late October, the Traces API is stable, and can be used with the OpenTelemetry Collector or using a Zipkin exporter to send traces data to New Relic.

An OpenTelemetry Exporter for C to use to send data to New Relic is coming soon, to be built using our new [C Telemetry SDK](https://github.com/newrelic/newrelic-telemetry-sdk-c).
