### ISSUE TITLE
Multi-threading performance issue

### ISSUE THREAD

**Issue by jodeev** [newrelic/c-sdk#28]
We are trying to get New Relic integrated with a new service written in rust, and so we are using a rust wrapper over NR's C SDK, info about which is at https://docs.rs/crate/newrelic/0.2.2. We have noticed a pretty sharp decline in throughput when New Relic was integrated and enabled. 

We ran some basic load testing with and without New Relic enabled. 

We dropped from roughly 49k req/sec down to about 4700 req/sec, more than a 90% decrease. When profiling the runtime, we found that a lot of time was spent waiting for mutex locks/unlocks when creating a transaction, thus reducing the effectiveness of our multithreaded application. Does the New Relic team have any advice on how to improve performance?

See more details in ticket: https://newrelic.zendesk.com/agent/tickets/445508

**Comment by Miriam-R** [comment]
This is closed per Zendesk notes & confirmed with Solutions consultant

**Comment by e-volusian** [comment]
@jodee We're having the exact same issue with our Rust application. Did you ever get a satisfactory conclusion from New Relic, and are you able to share details? (We are working with New Relic as well)
