### ISSUE TITLE
Adaptive misspelled in vendor/newrelic/axiom/nr_app_harvest.c

### ISSUE THREAD

**Issue by burgerrg** [newrelic/c-sdk#8]
```"Adpative sampling configuration. Connect: " NR_TIME_FMT```

**Comment by pyohannes** [comment]
Hi Bob! We fixed this glitch. The fix will go out with the next C SDK release.

Thanks for spotting and reporting that!

**Comment by Fahmy-Mohammed** [comment]
Implemented in [f5da260](https://github.com/newrelic/c-sdk/commit/f5da260cafd2ca46fb95d3303989cb302ab61257).  Released in C-SDK version 1.2.0.
